### PR TITLE
use same indy version for controller image

### PR DESCRIPTION
**Pull request by Echsecutor**

### CODE REVIEW

**Review by mgmgwi — APPROVED** [review]
lgtm

**Comment by mgmgwi** [comment]
@Echsecutor DCO is missing

**Review by solidnerd — APPROVED** [review]

**Comment by Echsecutor** [comment]
> @Echsecutor DCO is missing

ah, yes, thx. added.

**Comment by mgmgwi** [comment]
@Echsecutor -  I think we have a broken build at the moment (see https://github.com/hyperledger/indy-node-container/pull/110#issuecomment-1235294781), but I don't have time at the moment to investigate this further. I will try next week.

**Comment by Echsecutor** [comment]
@tsurai müssen wir podman mit in den container installieren? Das macht gerade einige Probleme
image

**Pull request merged**
